server:
  port: 9051

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  tymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: t